apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-job
spec:
  schedule: "* * * * *"
  template:
    spec:
      containers:
      - name: my-busybox
        image: busybox
        command: ["echo",  "This is my Job"]
      restartPolicy: Never
