apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
spec:
  completions: 5
  parallelism: 2
  template:
    spec:
      containers:
      - name: my-busybox
        image: busybox
        command: ["echo",  "This is my Job"]
      restartPolicy: Never
