apiVersion: v1
kind: Pod
metadata:
  name: nginx-secret
spec:
  initContainers:
   - name: busybox 
     image: busybox
     command: ["/bin/sh"]
     args: ["-c", "echo '<html><h1>This is init container</h1></html>' >> /work-dir/index.html"]
     volumeMounts: 
       - mountPath: "/work-dir"
         name: workdir
  containers:
   - name: nginx
     image: nginx:1.14.2
     ports:
       - containerPort: 80
     volumeMounts: 
       - mountPath: "/usr/share/nginx/html"
         name: workdir  
  volumes: 
   - name: workdir 
     emptyDir: {}
