apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

---

apiVersion: v1 
kind: Service 
metadata:
    name: my-svc
spec: 
    type: ClusterIP
    selector: 
        app: nginx   
    ports:
       - name: http 
         port: 30002
         targetPort: 80    