apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  serviceAccountName: k8s-sa
  containers:
   - name: nginx1
     image: nginx:1.14.2
     ports:
     - containerPort: 80
   - name: nginx2
     image: nginx:1.14.2
     ports:
     - containerPort: 80